### ISSUE TITLE
How to make the back/forward button appear?

### ISSUE THREAD

**Issue by Enclave-Tony-TRAN** [kf99916/ProgressWebViewController#12]
Hi, 

Thanks for your lib. I'm facing a problem with add back/forward button to the toolbar.

1. Init a navigation controller with root is ProgressWebViewController
2. Set the navigationVC.isToolbarHidden = false
3. Set .toolbarItemTypes = [.back, .forward, .reload, .activity] 
4. But only reload/activity button appear.

Can help on this?

**Comment by Enclave-Tony-TRAN** [comment]
Duplicate with exist.

**Comment by songxing10000** [comment]
After tossing and turning all afternoon, the toolbar finally showed up

`navigationController?.isToolbarHidden = false`
