### ISSUE TITLE
need support open local html file

### ISSUE THREAD

**Issue by chaoshenglu** [kf99916/ProgressWebViewController#3]
func load(_ url: URL) {
        guard let webView = webView else {
            return
        }
        if url.absoluteString.hasPrefix("http"){
            let request = createRequest(url: url)
            DispatchQueue.main.async {
                webView.load(request)
            }
        }else{
            webView.loadFileURL(url,allowingReadAccessTo:url)
        }
    }

**Comment by kf99916** [comment]
Hi @chaoshenglu, sorry for late reply. You can load the local html file like this way:
```
webView.load(Bundle.main.url(forResource: "xxx", withExtension:"html"))
```
