### ISSUE TITLE
Can not read cookie

### ISSUE THREAD

**Issue by mBilal5674** [kf99916/ProgressWebViewController#4]

**Comment by kf99916** [comment]
Can you give me more details?

**Comment by softwaredev740** [comment]
func progressWebViewController(_ controller: ProgressWebViewController, didFinish url: URL) {
        print(self.cookies)
        print(url.absoluteString)
    }


This code always return nil cookies although it's logged in the webview.

**Comment by kf99916** [comment]
If you want to read wkwebview's cookies, please leverage `HTTPCookieStorage.shared.cookies`. The `cookies` is for setting the wkwebview cookies from your app. I will rename the variable to make it more clear.

**Comment by kf99916** [comment]
Rename as `defaultCookies` in b4302375f4a0b9e505839a05a287126d90ae2b11
