### ISSUE TITLE
class ProgressWebViewController doesn't compile

### ISSUE THREAD

**Issue by apfelstrudelweb** [kf99916/ProgressWebViewController#5]
up to version 1.7.0 all worked fine.
But now I get the following compile error in line 321:
_Use of local variable 'refreshControl' before its declaration_

**Comment by kf99916** [comment]
I can compile it on Xcode 10.2.1 (The latest version). Could you give me more information? Thanks.

**Comment by apfelstrudelweb** [comment]
<img width="1137" alt="Bildschirmfoto 2019-05-06 um 11 08 22" src="https://user-images.githubusercontent.com/10762003/57216145-52e33680-6fef-11e9-808a-c0a9dd080171.png">
Hi, I'm using Xcode 10.1 - attached please find a screenshot with the error message

**Comment by kf99916** [comment]
Hi @apfelstrudelweb, sorry for late reply. If you still don't resolve the issue now, please refer to the solution: https://stackoverflow.com/questions/38513144/use-of-local-variable-before-its-declaration-error. Let me know if you need further help.
