### ISSUE TITLE
How we can open progressWebViewController by tapping on UITableView item?

### ISSUE THREAD

**Issue by shadowwalkersteam** [kf99916/ProgressWebViewController#6]
Currently the progressWebViewController is working fine when we launch it or open the URL on button click as you did in the DEMO app but now i have a tableview and there are multiple items in tableview how i can use this webview with tableview?

**Comment by kf99916** [comment]
2 ways I know:

- Init the webview controller in the `tableView(_:didSelectRowAt:)` and push/present it.
- Invoke `performSegue(withIdentifier:sender:)` in the `tableView(_:didSelectRowAt:)` and init the webview controller in the `prepare(for:sender:)`.

**Comment by shadowwalkersteam** [comment]
> 2 ways I know:
> 
> * Init the webview controller in the `tableView(_:didSelectRowAt:)` and push/present it.
> * Invoke `performSegue(withIdentifier:sender:)` in the `tableView(_:didSelectRowAt:)` and init the webview controller in the `prepare(for:sender:)`.

Currently im doing this way but no success it is opening a blank white page..
`func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if (indexPath.row == 0) {
            performSegue(withIdentifier: "shops", sender: self)
            let progressWebViewController = ProgressWebViewController()
            loadURL(progressWebViewController: progressWebViewController ,url: "https://cookiedoughboutique.com/ncc-parents-workshops-and-seminars/", title: "Events")
        }
    }`

**Comment by shadowwalkersteam** [comment]
> 2 ways I know:
> 
> * Init the webview controller in the `tableView(_:didSelectRowAt:)` and push/present it.
> * Invoke `performSegue(withIdentifier:sender:)` in the `tableView(_:didSelectRowAt:)` and init the webview controller in the `prepare(for:sender:)`.

Currently i'm doing this way but not getting success, it is opening blank white page.
`func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if (indexPath.row == 0) {
            performSegue(withIdentifier: "shops", sender: self)
            let progressWebViewController = ProgressWebViewController()
            loadURL(progressWebViewController: progressWebViewController ,url: "https://cookiedoughboutique.com/ncc-parents-workshops-and-seminars/", title: "Events")
        }
    }`

**Comment by shadowwalkersteam** [comment]
`private func loadURL(progressWebViewController: ProgressWebViewController, url: String, title: String) {
        let url = URL(string: url)
        progressWebViewController.disableZoom = true
        progressWebViewController.navigationItem.title = title
        //progressWebViewController.navigationWay = .browser
        //progressWebViewController.pullToRefresh = true
        progressWebViewController.toolbarItemTypes = [.back, .forward, .reload, .activity]
        progressWebViewController.url = url
        progressWebViewController.doneBarButtonItemPosition = .none
        progressWebViewController.headers = ["browser": "in-app browser"]
        progressWebViewController.tintColor = UIColor(named: "colorPrimaryDark")
    }`

this is the load url function

**Comment by kf99916** [comment]
Hi @shadowwalkersteam , sorry for late reply. You must config the destination in ```prepare(for:sender:)``` instead of  after ```performSegue ```. You can get more details from Apple document: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621490-prepare
