### ISSUE TITLE
Back and forward buttons are not showing

### ISSUE THREAD

**Issue by shadowwalkersteam** [kf99916/ProgressWebViewController#7]
im using this line but only reload and activity button are showing don't know why back and forward buttons are not showing

progressWebViewController.toolbarItemTypes = [.back, .forward, .reload, .activity]

**Comment by bogdan2ignatev** [comment]
I faced the same problem using the Swift Package Manager. It turned out that the button images were unavailable due to the lack of the framework bundles support in the SPM. The solution is to copy the assets to the main bundle.

**Comment by kf99916** [comment]
SPM doesn't support resources now: https://bugs.swift.org/browse/SR-2866. The temporary solution is copy assets manually just like @bogdan2ignatev  said or use CocoaPods.
