### ISSUE TITLE
How to call evaluateJavaScript

### ISSUE THREAD

**Issue by nobut** [kf99916/ProgressWebViewController#9]
<img width="887" alt="Screen Shot 2019-09-02 at 15 30 22" src="https://user-images.githubusercontent.com/28843198/64097350-9f206680-cd96-11e9-82af-1143220e9a3c.png">

**Comment by kf99916** [comment]
The ProgressWebViewController cannot call evaluateJavaScript now. I will add the feature in the feature. I appreciate you if you can help this issue.

**Comment by kf99916** [comment]
The issue is fixed: 01220cc7fab303a04ec542edf20111837bda5d30
